# Copyright 2017 (c) Michael Thomas (malinka) <malinka@entropy-development.com>
# Distributed under the terms of the GNU Affero General Public License v3

apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: pages
spec:
    template:
        metadata:
            labels:
                app: pages
        spec:
            containers:
                - name: pages
                  image: us.gcr.io/entropy-development/pages:0.2.0
                  ports:
                      - containerPort: 8080
                  env:
                      - name: PGHOST
                        valueFrom:
                            configMapKeyRef:
                                name: website-config
                                key: db.host
                      - name: PGPORT
                        valueFrom:
                            configMapKeyRef:
                                name: website-config
                                key: db.port
                      - name: PGDATABASE
                        valueFrom:
                            configMapKeyRef:
                                name: website-config
                                key: db.name
                      - name: PGUSER
                        valueFrom:
                            secretKeyRef:
                                name: website-secret
                                key: db.user
                      - name: PGPASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: website-secret
                                key: db.pass
---
apiVersion: v1
kind: Service
metadata:
    name: pages
    labels:
        app: pages
spec:
    type: LoadBalancer
    ports:
        - port: 8080
          protocol: TCP
          name: http-pages
    selector:
        app: pages
